apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-health-check
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-health-check
    app.kubernetes.io/part-of: nodejs-health-check
  name: nodejs-health-check
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-health-check
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-health-check
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/flacatus-tenant/nodejs-health-check/nodejs-health-check@sha256:4262ae024f1eec898448007f78a4a46685450368d8721bc9319d90040e370732
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
